### ISSUE TITLE
Where should I look to check if the builders are on Swiper 2?

### ISSUE THREAD

**Issue by markleusink** [camac/Swiper#12]
The release notes for the 2.0-alpha version mention that I have to remove and then add Swiper to any NSF that is using it. Has to do with updating the attached builders.

Where should I look to check that I've gone through this process in an NSF? I have a lot of NSF's using Swiper and want to keep track of the ones I've updated.

**Comment by camac** [comment]
Hi Mark,
Right click on your NSF Project and choose 'Project Properties' and then look at 'Builders'
You should see 2 Swiper builders in there if the old builders are still there.
