### ISSUE TITLE
9.0.1 FP8 - extension point for Swiper

### ISSUE THREAD

**Issue by kai-uwe-rommel** [camac/Swiper#13]
IBM published FP8 for Notes/Designer and I was told that this includes an extension point in Designer specifically for Swiper. Are you already aware of this? Will you adapt Swiper accordingly and create a new release?

**Comment by camac** [comment]
Hi Kai, I am aware! I have been working with IBM to make this happen : )

I have written a blog post last week with some details about the rollout
http://camerongregor.com/2017/03/08/swiper-fp8-rollout/

The short summary is that there is an '2.0.0alpha' release available right now in the releases section
https://github.com/camac/Swiper/releases

So far I have only had good reports from people who have been testing so in the next few days I will be adding 1 or 2 minor things and then releasing the final version 2.0.0 and updating OpenNTF as well

**Comment by kai-uwe-rommel** [comment]
Thanks a lot!
