### ISSUE TITLE
Error message No acceptable features found when installing in Domino Designer 12.0

### ISSUE THREAD

**Issue by sven-olding** [camac/Swiper#26]
I am trying to install the latest version 2.0.1 into Domino Designer 12.0 via the menu File -> Application -> Install... and just get the mentioned error message 

![image](https://user-images.githubusercontent.com/39855591/123269554-628ba500-d4ff-11eb-85d4-712b0df7eac7.png)

**Comment by perlausten** [comment]
Works for me (in Domino Designer 12.0.2)
<img width="403" alt="image" src="https://user-images.githubusercontent.com/208687/202691911-8f620e3d-9ff7-4100-bf7a-05f8782a7ac0.png">

**Comment by sven-olding** [comment]
Yes, can confirm it is now working in 12.0.2 (64 bit)...
