### ISSUE TITLE
View is unfiltered

### ISSUE THREAD

**Issue by tinusriyanto** [camac/Swiper#4]
Auto Export is On
Built Automatically is On
This is the log as you requested. It seems that Swiper is not triggered at all even if I manually built the project. So far the only way I could make filter to work is to select each design element and manually do Filter Selected.
[swiper-log.txt](https://github.com/camac/Swiper/files/38689/swiper-log.txt)

**Comment by camac** [comment]
hi Tinus thanks for this, from the log file it looks as though swiper is
not even starting up for that project.

can you
turn logging on
remove swiper from project
add swiper to project
make small change to a view
save (hopefully this triggers build)
build (in case it didn't trigger build
turn logging off

and send the file again? there may be more than one log file after this so
check it is the latest.

also can you let me know exact version of domino designer ? I will check
for compatibility

**Comment by tinusriyanto** [comment]
Hi Cameron, that is a very quick reply.
Done what suggested and now it is filtering the view when I save it.
Designer version is Revision 20130309.0748 (Release 9.0)
Here is the log just in case you still need it
[swiper-log-2.txt](https://github.com/camac/Swiper/files/38740/swiper-log-2.txt)

Will try this in another NSF with an existing ODP to see if the issue come up again.

**Comment by camac** [comment]
Hi Tinus, I think I know what may have happened (and if you can confirm that would be great)
Is it possible that when you added swiper you had not yet set up source control sync for that project? i.e. did you add swiper and then set up source control?

if it is done in this order then swiper will not install properly.

I have just released a new version 1.0.2 which will prevent swiper from adding to a project if source control is not yet set up for that project.

If this is applicable to your case then that is good news as this release should prevent this bug happening again

**Comment by tinusriyanto** [comment]
Yes, you are correct. For that particular project I remember adding swiper first then creating ODP.
